In [1]:
import pandas as pd
import os
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [13]:
row_numbers = np.arange(5,16,1)
row_numbers

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
res = pd.DataFrame(columns=('column_selected','precision','recall','finding_rate','cross_val'))

def load_one_version_method_matrix(matrix_path):
    print(matrix_path)
    return pd.read_csv(matrix_path,header=None, names = ['column_selected','precision','recall','finding_rate','cross_val'] )
filePath = "rows_selected/"
for row_number in row_numbers:
    selected_row_number = "Rows_selected_"+str(row_number)+"_result.csv"
    result = load_one_version_method_matrix(filePath+selected_row_number)
    sorted_result = result.sort_values(by="finding_rate" , ascending=False) 
    res = res.append(sorted_result[0:5], ignore_index=True)


rows_selected/Rows_selected_5_result.csv
rows_selected/Rows_selected_6_result.csv
rows_selected/Rows_selected_7_result.csv
rows_selected/Rows_selected_8_result.csv
rows_selected/Rows_selected_9_result.csv
rows_selected/Rows_selected_10_result.csv
rows_selected/Rows_selected_11_result.csv
rows_selected/Rows_selected_12_result.csv
rows_selected/Rows_selected_13_result.csv
rows_selected/Rows_selected_14_result.csv
rows_selected/Rows_selected_15_result.csv


In [21]:
res

column_selected  precision    recall  \
0                                    (0, 1, 2, 5, 13)   0.978102  0.905405   
1                                   (4, 6, 7, 10, 14)   1.000000  0.844595   
2                                    (0, 1, 3, 4, 13)   0.992701  0.918919   
3                                    (0, 1, 7, 9, 10)   0.985507  0.918919   
4                                    (0, 4, 6, 9, 10)   0.992366  0.878378   
5                                (0, 3, 6, 9, 10, 13)   0.978102  0.905405   
6                                 (4, 6, 7, 8, 9, 13)   0.979021  0.945946   
7                               (0, 7, 9, 11, 12, 13)   0.985185  0.898649   
8                               (0, 6, 8, 10, 13, 14)   0.985612  0.925676   
9                                 (0, 2, 5, 7, 9, 13)   0.978873  0.939189   
10                          (0, 5, 6, 10, 11, 13, 14)   0.977273  0.871622   
11                            (0, 1, 2, 3, 7, 11, 13)   0.978723  0.932432   
12                           (0, 2, 5, 7, 10, 12, 13)   0.978417  0.918919   
13                            (1, 3, 4, 5, 8, 13, 14)   0.978261  0.912162   
14                            (1, 2, 3, 4, 8, 11, 13)   0.985185  0.898649   
15                         (0, 2, 4, 6, 7, 9, 10, 13)   0.985714  0.932432   
16                       (0, 2, 5, 7, 10, 11, 12, 14)   1.000000  0.905405   
17                      (3, 4, 7, 10, 11, 12, 13, 14)   0.971223  0.912162   
18                         (0, 3, 4, 5, 7, 9, 10, 11)   0.992188  0.858108   
19                        (0, 3, 4, 7, 8, 12, 13, 14)   0.985401  0.912162   
20                      (0, 1, 2, 3, 7, 8, 9, 11, 13)   0.992701  0.918919   
21                     (0, 1, 4, 5, 7, 9, 10, 11, 13)   0.992754  0.925676   
22                     (0, 1, 4, 5, 6, 9, 10, 12, 13)   0.992806  0.932432   
23                     (1, 3, 4, 6, 7, 9, 10, 11, 13)   0.978417  0.918919   
24                    (0, 1, 4, 7, 8, 11, 12, 13, 14)   0.992754  0.925676   
25                  (0, 2, 3, 4, 7, 8, 9, 10, 11, 13)   0.992857  0.939189   
26                 (0, 2, 4, 5, 8, 9, 10, 11, 13, 14)   0.992908  0.945946   
27                  (0, 2, 4, 5, 6, 8, 9, 11, 13, 14)   0.992647  0.912162   
28                 (0, 1, 2, 7, 8, 9, 10, 12, 13, 14)   0.978417  0.918919   
29                   (0, 1, 2, 4, 5, 6, 7, 9, 12, 13)   0.985075  0.891892   
30             (0, 1, 2, 3, 5, 7, 10, 11, 12, 13, 14)   0.972028  0.939189   
31             (0, 1, 2, 4, 5, 7, 10, 11, 12, 13, 14)   0.978873  0.939189   
32              (0, 2, 4, 5, 6, 8, 9, 10, 11, 13, 14)   0.985401  0.912162   
33             (0, 1, 3, 7, 8, 9, 10, 11, 12, 13, 14)   0.978723  0.932432   
34              (1, 2, 3, 5, 7, 8, 9, 10, 11, 12, 13)   0.971014  0.905405   
35            (0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 13, 14)   0.978571  0.925676   
36          (0, 1, 2, 3, 4, 5, 6, 10, 11, 12, 13, 14)   0.985401  0.912162   
37          (0, 2, 3, 4, 5, 7, 9, 10, 11, 12, 13, 14)   0.985816  0.939189   
38           (0, 1, 2, 3, 4, 5, 6, 8, 10, 12, 13, 14)   0.985714  0.932432   
39          (0, 1, 2, 3, 5, 6, 9, 10, 11, 12, 13, 14)   0.985401  0.912162   
40       (0, 1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14)   0.964539  0.918919   
41        (0, 1, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13)   0.992857  0.939189   
42       (0, 1, 2, 3, 4, 5, 6, 8, 10, 11, 12, 13, 14)   1.000000  0.898649   
43        (0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 13, 14)   0.985714  0.932432   
44       (0, 1, 2, 3, 4, 5, 6, 7, 10, 11, 12, 13, 14)   0.992424  0.885135   
45    (0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)   0.992754  0.925676   
46    (0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14)   0.985185  0.898649   
47     (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)   0.977941  0.898649   
48     (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14)   0.992701  0.918919   
49    (0, 1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)   0.992754  0.925676   
50  (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...   0.97

# same in the Classification

In [53]:
import pandas as pd
import os
filePath = "AlltheMatrix/"
single_version_file_path = filePath + 'modified_single_version-ck-oo.csv'
changed_file_path = filePath + 'modified_change_metrics.csv'
bug_matrix_path = filePath + 'modified_bug-metrics.csv' 
# complexity_code_change_path = 



filePathNowusing = changed_file_path

def load_one_version_method_matrix(matrix_path):
    print(matrix_path)
    return pd.read_csv(matrix_path)

changed_matrix = load_one_version_method_matrix(filePathNowusing)
print(f'lens: {len(changed_matrix.columns.values)}')

startindex = 0
endindex = 0
for i, column in enumerate(changed_matrix.columns.values):
    if(column == 'classname'):
        startindex = i
    elif (column == 'bugs'):
        endindex = i
print(f'start:{startindex},end:{endindex}') 
target = changed_matrix['bugs'].values
data = changed_matrix.values[:,startindex+1:endindex]
print(target.shape)
print(data.shape)

#shuffleIndex
import numpy as np
shuffle_index = np.random.permutation(997)
target, data = target[shuffle_index], data[shuffle_index]

#shuffleIndex
import numpy as np
shuffle_index = np.random.permutation(997)
target, data = target[shuffle_index], data[shuffle_index]

def get_selected_rows(columncombation,X_data):
    flag = False
    for i in columncombation:
        if(flag == False):
            c = X_data[:,i].T
            flag = True
        else:
            c = np.vstack((c,X_data[:,i].T))
    X_train_selected = c.T 
    return X_train_selected
def predicted_bugNum_vs_true_bugNum(Y_test_predict,Y_test_bugs):
    n = 0
    bugrowcount = 0
    for i in range(0,len(Y_test_predict)):
        if(Y_test_bugs[i]!=False):
            bugrowcount += 1
            if(Y_test_predict[i]==Y_test_bugs[i]):
                n=n+1
#    print(n/bugrowcount,n,bugrowcount)
    return n/bugrowcount,n

AlltheMatrix/modified_change_metrics.csv
lens: 23
start:1,end:17
(997,)
(997, 15)


In [55]:
#split the train set and the test set
X_train = data[:700]
X_test = data[700:]
Y_train = target[:700]
Y_test = target[700:]
print(X_train,Y_train.shape)
#train a binary classifier
Y_train_bugs = (Y_train > 0)
Y_test_bugs = (Y_test > 0 )
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

#hardCopy to test the selected rows
columncombation_j = (0, 6, 8, 10, 13, 14)
X_train_selected = get_selected_rows(columncombation_j,X_train)
X_test_selected = get_selected_rows(columncombation_j,X_test)


forest_clf = RandomForestClassifier(n_estimators = 10)
forest_clf.fit(X_train_selected,Y_train_bugs)

cross_result = cross_val_score(forest_clf, X_train_selected, Y_train_bugs, cv = 10, scoring = 'accuracy')
Y_forest_predict = forest_clf.predict(X_train_selected)

from sklearn.metrics import precision_score, recall_score
forst_precision = precision_score(Y_train_bugs, Y_forest_predict)
forst_recall = recall_score(Y_train_bugs, Y_forest_predict)
print(f'Forest_accurancy is {forst_precision}')
print(f'Forest_recall is {forst_recall}')

print(columncombation_j)
#    print(X_train_selected)
Y_test_predict = forest_clf.predict(X_test_selected)

findingRate = predicted_bugNum_vs_true_bugNum(Y_test_predict,Y_test_bugs)
print(f'fingdingrate = {findingRate}')

[[38 13 0 ... 4.84211 333.14300000000003 69.9451]
 [40 11 0 ... 8.25 333.14300000000003 84.0767]
 [55 4 0 ... -0.963636 258.143 62.4695]
 ...
 [6 3 0 ... -2.33333 113.85700000000001 20.323]
 [65 7 0 ... -2.21538 367.0 60.7758]
 [11 4 0 ... 0.363636 282.0 82.7755]] (700,)
Forest_accurancy is 0.9848484848484849
Forest_recall is 0.9027777777777778
(0, 6, 8, 10, 13, 14)
fingdingrate = (0.5161290322580645, 32)
