In [26]:

from imblearn.over_sampling import RandomOverSampler
from collections import Counter
import pandas as pd
import os
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score, recall_score
import MLSE_Class as MLSE

In [27]:
??MLSE

In [4]:
ros = RandomOverSampler(random_state=0)

X_train_eclipse,Y_train_bugs_eclipse,X_test_eclipse,Y_test_bugs_eclipse = MLSE.classification_binary("differentSoftware/eclipse/eclipse_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_eclipse, y_resampled_eclipse = ros.fit_resample(X_train_eclipse, Y_train_bugs_eclipse)
X_train_equinox,Y_train_bugs_equinox,X_test_equinox,Y_test_bugs_equinox = MLSE.classification_binary("differentSoftware/equinox/equinox_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_equinox, y_resampled_equinox = ros.fit_resample(X_train_equinox, Y_train_bugs_equinox)
X_train_pde,Y_train_bugs_pde,X_test_pde,Y_test_bugs_pde = MLSE.classification_binary("differentSoftware/pde/pde_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_pde, y_resampled_pde = ros.fit_resample(X_train_pde, Y_train_bugs_pde)

X_train_lucene,Y_train_bugs_lucene,X_test_lucene,Y_test_bugs_lucene = MLSE.classification_binary("differentSoftware/lucene/lucene_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_lucene, y_resampled_lucene = ros.fit_resample(X_train_lucene, Y_train_bugs_lucene)

X_train_mylyn,Y_train_bugs_mylyn,X_test_mylyn,Y_test_bugs_mylyn = MLSE.classification_binary("differentSoftware/mylyn/mylyn_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_mylyn, y_resampled_mylyn = ros.fit_resample(X_train_lucene, Y_train_bugs_lucene)


AlltheMatrix/differentSoftware/eclipse/eclipse_all_data.csv
lens: 50
start:2,end:43
(997,)
the data shape is (997, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[0 0 0 ... 0 3 9]
 [61 12 9 ... 34 290 1603]
 [3 0 0 ... 0 2 23]
 ...
 [32 1 1 ... 17 26 111]
 [8 0 0 ... 0 20 31]
 [0 0 0 ... 2 3 7]] (698,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/equinox/equinox_all_data.csv
lens: 50
start:2,end:43
(324,)
the data shape is (324, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[5 1 0 ... 0 5 9]
 [1 0 0 ... 0 2 8]
 [3 0 0 ... 0 4 5]
 ...
 [1 0 0 ... 0 2 4]
 [1 0 0 ... 0 2 14]
 [1 0 0 ... 0 1 3]] (227,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/pde/pde_all_data.csv
lens: 50
start:2,end:43
(1497,)
the data shape is (1497, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[1 0 0 ... 0 2 95]
 [1 1 0 ... 0 14 94]
 [0 0 0 ... 0 2 123]
 ...
 [0 0 0 ... 0 2 6]
 [9 0 0 ... 0 2 9]
 [3 0 0 ... 0 2 17]] (1048,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatr

In [62]:
# result1 = [None]*4
# result2 = [result1]*5
# result = [result2]*5
result = []
result_a = []
result_r = []
result_p = []
result_f = []
import MLSE_Class as MLSE

In [55]:
??MLSE

In [63]:
list11 = [X_resampled_eclipse, X_resampled_pde,X_resampled_equinox,X_resampled_lucene,X_resampled_mylyn]
list22 = [y_resampled_eclipse,y_resampled_pde,y_resampled_equinox,y_resampled_lucene,y_resampled_mylyn]
list33 = [X_test_eclipse, X_test_pde,X_test_equinox,X_test_lucene,X_test_mylyn]
list44 = [Y_test_bugs_eclipse,Y_test_bugs_pde,Y_test_bugs_equinox,Y_test_bugs_lucene,Y_test_bugs_mylyn]
list_name = ['X_train_eclipse', 'X_train_pde','X_train_equinox','X_train_lucene','X_train_mylyn']
import MLSE_Class as MLSE
for i in range(len(list11)):
    for j in range(len(list11)):
        print(list_name[i],list_name[j])
        print(i,j)
        result = MLSE.neuralNetworks(list11[i],list22[i],list33[j],list44[j])
        result_a += result[0]
        result_r += result[1]
        result_p += result[2]
        result_f += result[3]
        print("·············~·······")

X_train_eclipse X_train_eclipse
0 0
The test accuracy score is 0.6989966555183946
The test recall score is 0.7586206896551724
The test precision score is 0.36666666666666664
The test f1 score is 0.4943820224719101
·············~·······
X_train_eclipse X_train_pde
0 1
The test accuracy score is 0.5412026726057907
The test recall score is 0.6166666666666667
The test precision score is 0.16818181818181818
The test f1 score is 0.2642857142857143
·············~·······
X_train_eclipse X_train_equinox
0 2
The test accuracy score is 0.7525773195876289
The test recall score is 0.5681818181818182
The test precision score is 0.8333333333333334
The test f1 score is 0.6756756756756758
·············~·······
X_train_eclipse X_train_lucene
0 3
The test accuracy score is 0.6038647342995169
The test recall score is 0.5789473684210527
The test precision score is 0.12941176470588237
The test f1 score is 0.2115384615384616
·············~·······
X_train_eclipse X_train_mylyn
0 4
The test accuracy score is 0

In [53]:
#         mclf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(100, 100))

np.mean(result_a),np.mean(result_r),np.mean(result_p),np.mean(result_f)

(0.640339162045044, 0.5306529175603586, 0.282641590208881, 0.33994980627773946)

In [58]:
#         mclf = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(50,100,50))
np.mean(result_a),np.mean(result_r),np.mean(result_p),np.mean(result_f)

(0.6378798359434483,
 0.5313338832975857,
 0.2877666634651665,
 0.3416469954817795)

In [61]:
#         mclf = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(50,100,50),learning_rate = "adapative")
np.mean(result_a),np.mean(result_r),np.mean(result_p),np.mean(result_f)

(0.6267956568665223,
 0.5448847824891382,
 0.27978941176303496,
 0.3406530861309988)

In [64]:
#         mclf = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(50,100,50),activation = "logistic")
np.mean(result_a),np.mean(result_r),np.mean(result_p),np.mean(result_f)

(0.6434840236526672,
 0.5423605565638233,
 0.3003023277158391,
 0.3473907743376538)