In [9]:

from imblearn.over_sampling import RandomOverSampler
from collections import Counter
import pandas as pd
import os
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score, recall_score

In [10]:
import MLSE_Class as MLSE
X_train_eclipse,Y_train_bugs_eclipse,X_test_eclipse,Y_test_bugs_eclipse = MLSE.classification_binary("differentSoftware/eclipse/eclipse_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_train_equinox,Y_train_bugs_equinox,X_test_equinox,Y_test_bugs_equinox = MLSE.classification_binary("differentSoftware/equinox/equinox_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_train_pde,Y_train_bugs_pde,X_test_pde,Y_test_bugs_pde = MLSE.classification_binary("differentSoftware/pde/pde_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_train_lucene,Y_train_bugs_lucene,X_test_lucene,Y_test_bugs_lucene = MLSE.classification_binary("differentSoftware/lucene/lucene_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_train_mylyn,Y_train_bugs_mylyn,X_test_mylyn,Y_test_bugs_mylyn = MLSE.classification_binary("differentSoftware/mylyn/mylyn_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")

AlltheMatrix/differentSoftware/eclipse/eclipse_all_data.csv
lens: 50
start:2,end:43
(997,)
the data shape is (997, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[9 1 0 ... 8 9 47]
 [2 0 0 ... 0 8 22]
 [8 2 1 ... 2 4 55]
 ...
 [0 0 0 ... 0 5 9]
 [8 1 1 ... 0 4 48]
 [14 0 0 ... 2 8 59]] (798,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/equinox/equinox_all_data.csv
lens: 50
start:2,end:43
(324,)
the data shape is (324, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[0 0 0 ... 0 6 18]
 [1 0 0 ... 0 1 1]
 [3 0 0 ... 1 13 69]
 ...
 [2 0 0 ... 7 18 108]
 [1 0 0 ... 0 0 0]
 [2 1 0 ... 0 1 8]] (259,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/pde/pde_all_data.csv
lens: 50
start:2,end:43
(1497,)
the data shape is (1497, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[2 0 0 ... 0 1 32]
 [0 0 0 ... 0 5 17]
 [1 0 0 ... 0 7 32]
 ...
 [0 0 0 ... 1 7 48]
 [5 0 0 ... 1 2 17]
 [0 0 0 ... 0 2 2]] (1198,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/dif

# eclipse as train set

In [5]:
print(f'Y_train_bugs_eclipse:{sorted(Counter(Y_train_bugs_eclipse).items())}')
print(f'Y_train_bugs_equinox:{sorted(Counter(Y_train_bugs_equinox).items())}')
print(f'Y_train_bugs_pde:{sorted(Counter(Y_train_bugs_pde).items())}')
print(f'Y_train_bugs_lucene:{sorted(Counter(Y_train_bugs_lucene).items())}')
print(f'Y_train_bugs_mylyn:{sorted(Counter(Y_train_bugs_mylyn).items())}')


Y_train_bugs_eclipse:[(False, 632), (True, 166)]
Y_train_bugs_equinox:[(False, 154), (True, 105)]
Y_train_bugs_pde:[(False, 1037), (True, 161)]
Y_train_bugs_lucene:[(False, 504), (True, 49)]
Y_train_bugs_mylyn:[(False, 1286), (True, 204)]


In [28]:
list1 = [X_train_eclipse, X_train_pde,X_train_equinox,X_train_lucene,X_train_mylyn]
list2 = [Y_train_bugs_eclipse,Y_train_bugs_pde,Y_train_bugs_equinox,Y_train_bugs_lucene,Y_train_bugs_mylyn]
list3 = [X_test_eclipse, X_test_pde,X_test_equinox,X_test_lucene,X_test_mylyn]
list4 = [Y_test_bugs_eclipse,Y_test_bugs_pde,Y_test_bugs_equinox,Y_test_bugs_lucene,Y_test_bugs_mylyn]
list_name = ['X_train_eclipse', 'X_train_pde','X_train_equinox','X_train_lucene','X_train_mylyn']
for i in range(len(list1)):
    for j in range(len(list1)):
        print(list_name[i],list_name[j])
        if (i!=j):
            MLSE.logisticRegression(list1[i],list2[i],list1[j],list2[j])
        elif (i==j):
            MLSE.logisticRegression(list1[i],list2[i],list3[j],list4[j])           
        print("·············~·······")

X_train_eclipse X_train_eclipse
The test accuracy score is 0.7939698492462312
The test recall score is 0.6666666666666666
The test precision score is 0.4814814814814815
The test f1 score is 0.5591397849462365
·············~·······
X_train_eclipse X_train_pde
The test accuracy score is 0.6994991652754591
The test recall score is 0.41463414634146345
The test precision score is 0.2048192771084337
The test f1 score is 0.27419354838709675
·············~·······
X_train_eclipse X_train_equinox
The test accuracy score is 0.6525096525096525
The test recall score is 0.21782178217821785
The test precision score is 0.6666666666666666
The test f1 score is 0.3283582089552239
·············~·······
X_train_eclipse X_train_lucene
The test accuracy score is 0.786618444846293
The test recall score is 0.24074074074074076
The test precision score is 0.14444444444444443
The test f1 score is 0.18055555555555552
·············~·······
X_train_eclipse X_train_mylyn
The test accuracy score is 0.4523489932885906


In [2]:
ros = RandomOverSampler(random_state=0)

In [5]:
X_train_eclipse,Y_train_bugs_eclipse,X_test_eclipse,Y_test_bugs_eclipse = MLSE.classification_binary("differentSoftware/eclipse/eclipse_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_eclipse, y_resampled_eclipse = ros.fit_resample(X_train_eclipse, Y_train_bugs_eclipse)
X_train_equinox,Y_train_bugs_equinox,X_test_equinox,Y_test_bugs_equinox = MLSE.classification_binary("differentSoftware/equinox/equinox_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_equinox, y_resampled_equinox = ros.fit_resample(X_train_equinox, Y_train_bugs_equinox)
X_train_pde,Y_train_bugs_pde,X_test_pde,Y_test_bugs_pde = MLSE.classification_binary("differentSoftware/pde/pde_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_pde, y_resampled_pde = ros.fit_resample(X_train_pde, Y_train_bugs_pde)

X_train_lucene,Y_train_bugs_lucene,X_test_lucene,Y_test_bugs_lucene = MLSE.classification_binary("differentSoftware/lucene/lucene_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_lucene, y_resampled_lucene = ros.fit_resample(X_train_lucene, Y_train_bugs_lucene)

X_train_mylyn,Y_train_bugs_mylyn,X_test_mylyn,Y_test_bugs_mylyn = MLSE.classification_binary("differentSoftware/mylyn/mylyn_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_mylyn, y_resampled_mylyn = ros.fit_resample(X_train_lucene, Y_train_bugs_lucene)


AlltheMatrix/differentSoftware/eclipse/eclipse_all_data.csv
lens: 50
start:2,end:43
(997,)
the data shape is (997, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[0 0 0 ... 0 204 204]
 [7 1 0 ... 0 2 35]
 [12 1 1 ... 13 17 74]
 ...
 [4 1 1 ... 0 8 13]
 [22 5 2 ... 1 1 82]
 [8 0 0 ... 0 3 63]] (798,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/equinox/equinox_all_data.csv
lens: 50
start:2,end:43
(324,)
the data shape is (324, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[1 0 0 ... 0 1 2]
 [1 0 0 ... 0 1 1]
 [1 0 0 ... 0 2 10]
 ...
 [1 0 0 ... 0 2 8]
 [4 1 0 ... 0 6 101]
 [29 5 1 ... 0 5 174]] (259,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/pde/pde_all_data.csv
lens: 50
start:2,end:43
(1497,)
the data shape is (1497, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[1 0 0 ... 0 3 33]
 [0 0 0 ... 0 2 2]
 [16 1 0 ... 0 6 243]
 ...
 [2 1 1 ... 0 5 11]
 [36 2 0 ... 0 3 494]
 [2 0 0 ... 0 4 18]] (1198,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
Allth

In [8]:
list11 = [X_resampled_eclipse, X_resampled_pde,X_resampled_equinox,X_resampled_lucene,X_resampled_mylyn]
list22 = [y_resampled_eclipse,y_resampled_pde,y_resampled_equinox,y_resampled_lucene,y_resampled_mylyn]
list33 = [X_test_eclipse, X_test_pde,X_test_equinox,X_test_lucene,X_test_mylyn]
list44 = [Y_test_bugs_eclipse,Y_test_bugs_pde,Y_test_bugs_equinox,Y_test_bugs_lucene,Y_test_bugs_mylyn]
list_name = ['X_train_eclipse', 'X_train_pde','X_train_equinox','X_train_lucene','X_train_mylyn']

for i in range(len(list11)):
    for j in range(len(list11)):
        print(list_name[i],list_name[j])
        if (i!=j):
            MLSE.neuralNetworks(list11[i],list22[i],list33[j],list44[j])
        elif (i==j):
            MLSE.neuralNetworks(list11[i],list22[i],list33[j],list44[j])           
        print("·············~·······")

X_train_eclipse X_train_eclipse
The test accuracy score is 0.7427135678391961
The test recall score is 0.7222222222222222
The test precision score is 0.3875380970608283
The test f1 score is 0.5042787493449705
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_pde
The test accuracy score is 0.5525083612040134
The test recall score is 0.6619047619047619
The test precision score is 0.18977976034760297
The test f1 score is 0.2946779755880118
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_equinox
The test accuracy score is 0.5169230769230769
The test recall score is 0.7076923076923076
The test precision score is 0.4584596002209323
The test f1 score is 0.5477998856725689
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_lucene
The test accuracy score is 0.6579710144927536
The test recall score is 0.8444444444444443
The test precision score is 0.14564102564102566
The test f1 score is 0.24778477693659448
~~~~~~~~~~~~~~~~

In [11]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled_eclipse, y_resampled_eclipse = smote_enn.fit_resample(X_train_eclipse, Y_train_bugs_eclipse)
X_resampled_equinox, y_resampled_equinox = smote_enn.fit_resample(X_train_equinox, Y_train_bugs_equinox)
X_resampled_pde, y_resampled_pde = smote_enn.fit_resample(X_train_pde, Y_train_bugs_pde)
X_resampled_lucene, y_resampled_lucene = smote_enn.fit_resample(X_train_lucene, Y_train_bugs_lucene)
X_resampled_mylyn, y_resampled_mylyn = smote_enn.fit_resample(X_train_lucene, Y_train_bugs_lucene)

In [13]:
list11 = [X_resampled_eclipse, X_resampled_pde,X_resampled_equinox,X_resampled_lucene,X_resampled_mylyn]
list22 = [y_resampled_eclipse,y_resampled_pde,y_resampled_equinox,y_resampled_lucene,y_resampled_mylyn]
list33 = [X_test_eclipse, X_test_pde,X_test_equinox,X_test_lucene,X_test_mylyn]
list44 = [Y_test_bugs_eclipse,Y_test_bugs_pde,Y_test_bugs_equinox,Y_test_bugs_lucene,Y_test_bugs_mylyn]
list_name = ['X_train_eclipse', 'X_train_pde','X_train_equinox','X_train_lucene','X_train_mylyn']
for i in range(len(list11)):
    for j in range(len(list11)):
        print(list_name[i],list_name[j])
        if (i!=j):
            MLSE.RandomForest(list11[i],list22[i],list33[j],list44[j])
        elif (i==j):
            MLSE.RandomForest(list11[i],list22[i],list33[j],list44[j])           
        print("·············~·······")

X_train_eclipse X_train_eclipse
The test accuracy score is 0.8321608040201005
The test recall score is 0.8514285714285714
The test precision score is 0.5141026087819436
The test f1 score is 0.6409229970921655
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_pde
The test accuracy score is 0.737123745819398
The test recall score is 0.574468085106383
The test precision score is 0.3156302038472581
The test f1 score is 0.4072066571538334
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_equinox
The test accuracy score is 0.7569230769230769
The test recall score is 0.45714285714285713
The test precision score is 0.6864468864468863
The test f1 score is 0.5482726423902895
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_lucene
The test accuracy score is 0.8579710144927537
The test recall score is 0.411764705882353
The test precision score is 0.4218954248366013
The test f1 score is 0.4165418894830659
~~~~~~~~~~~~~~~~~~~~~