In [1]:

from imblearn.over_sampling import RandomOverSampler
from collections import Counter
import pandas as pd
import os
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score, recall_score

In [2]:
import MLSE_Class as MLSE
X_train_eclipse,Y_train_bugs_eclipse,X_test_eclipse,Y_test_bugs_eclipse = MLSE.classification_binary("differentSoftware/eclipse/eclipse_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_train_equinox,Y_train_bugs_equinox,X_test_equinox,Y_test_bugs_equinox = MLSE.classification_binary("differentSoftware/equinox/equinox_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_train_pde,Y_train_bugs_pde,X_test_pde,Y_test_bugs_pde = MLSE.classification_binary("differentSoftware/pde/pde_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_train_lucene,Y_train_bugs_lucene,X_test_lucene,Y_test_bugs_lucene = MLSE.classification_binary("differentSoftware/lucene/lucene_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_train_mylyn,Y_train_bugs_mylyn,X_test_mylyn,Y_test_bugs_mylyn = MLSE.classification_binary("differentSoftware/mylyn/mylyn_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")

AlltheMatrix/differentSoftware/eclipse/eclipse_all_data.csv
lens: 50
start:2,end:43
(997,)
the data shape is (997, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[0 0 0 ... 0 9 30]
 [14 3 1 ... 0 10 79]
 [5 0 0 ... 0 4 7]
 ...
 [17 0 0 ... 0 0 3]
 [7 0 0 ... 0 5 51]
 [2 1 1 ... 0 7 14]] (698,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/equinox/equinox_all_data.csv
lens: 50
start:2,end:43
(324,)
the data shape is (324, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[2 1 0 ... 0 11 27]
 [1 0 0 ... 0 4 14]
 [0 0 0 ... 0 4 17]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 3 3]
 [1 0 0 ... 0 1 101]] (227,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/pde/pde_all_data.csv
lens: 50
start:2,end:43
(1497,)
the data shape is (1497, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[4 0 0 ... 0 3 7]
 [4 1 0 ... 0 4 51]
 [7 1 1 ... 0 2 86]
 ...
 [0 0 0 ... 0 6 53]
 [1 0 0 ... 0 2 14]
 [3 0 0 ... 0 5 54]] (1048,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/di

# eclipse as train set

In [3]:
print(f'Y_train_bugs_eclipse:{sorted(Counter(Y_train_bugs_eclipse).items())}')
print(f'Y_train_bugs_equinox:{sorted(Counter(Y_train_bugs_equinox).items())}')
print(f'Y_train_bugs_pde:{sorted(Counter(Y_train_bugs_pde).items())}')
print(f'Y_train_bugs_lucene:{sorted(Counter(Y_train_bugs_lucene).items())}')
print(f'Y_train_bugs_mylyn:{sorted(Counter(Y_train_bugs_mylyn).items())}')


Y_train_bugs_eclipse:[(False, 553), (True, 145)]
Y_train_bugs_equinox:[(False, 139), (True, 88)]
Y_train_bugs_pde:[(False, 904), (True, 144)]
Y_train_bugs_lucene:[(False, 443), (True, 41)]
Y_train_bugs_mylyn:[(False, 1125), (True, 178)]


In [28]:
list1 = [X_train_eclipse, X_train_pde,X_train_equinox,X_train_lucene,X_train_mylyn]
list2 = [Y_train_bugs_eclipse,Y_train_bugs_pde,Y_train_bugs_equinox,Y_train_bugs_lucene,Y_train_bugs_mylyn]
list3 = [X_test_eclipse, X_test_pde,X_test_equinox,X_test_lucene,X_test_mylyn]
list4 = [Y_test_bugs_eclipse,Y_test_bugs_pde,Y_test_bugs_equinox,Y_test_bugs_lucene,Y_test_bugs_mylyn]
list_name = ['X_train_eclipse', 'X_train_pde','X_train_equinox','X_train_lucene','X_train_mylyn']
for i in range(len(list1)):
    for j in range(len(list1)):
        print(list_name[i],list_name[j])
        if (i!=j):
            MLSE.logisticRegression(list1[i],list2[i],list1[j],list2[j])
        elif (i==j):
            MLSE.logisticRegression(list1[i],list2[i],list3[j],list4[j])           
        print("·············~·······")

X_train_eclipse X_train_eclipse
The test accuracy score is 0.7939698492462312
The test recall score is 0.6666666666666666
The test precision score is 0.4814814814814815
The test f1 score is 0.5591397849462365
·············~·······
X_train_eclipse X_train_pde
The test accuracy score is 0.6994991652754591
The test recall score is 0.41463414634146345
The test precision score is 0.2048192771084337
The test f1 score is 0.27419354838709675
·············~·······
X_train_eclipse X_train_equinox
The test accuracy score is 0.6525096525096525
The test recall score is 0.21782178217821785
The test precision score is 0.6666666666666666
The test f1 score is 0.3283582089552239
·············~·······
X_train_eclipse X_train_lucene
The test accuracy score is 0.786618444846293
The test recall score is 0.24074074074074076
The test precision score is 0.14444444444444443
The test f1 score is 0.18055555555555552
·············~·······
X_train_eclipse X_train_mylyn
The test accuracy score is 0.4523489932885906


In [14]:
ros = RandomOverSampler(random_state=0)

In [15]:
import MLSE_Class as MLSE
X_train_eclipse,Y_train_bugs_eclipse,X_test_eclipse,Y_test_bugs_eclipse = MLSE.classification_binary("differentSoftware/eclipse/eclipse_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_eclipse, y_resampled_eclipse = ros.fit_resample(X_train_eclipse, Y_train_bugs_eclipse)
X_train_equinox,Y_train_bugs_equinox,X_test_equinox,Y_test_bugs_equinox = MLSE.classification_binary("differentSoftware/equinox/equinox_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_equinox, y_resampled_equinox = ros.fit_resample(X_train_equinox, Y_train_bugs_equinox)
X_train_pde,Y_train_bugs_pde,X_test_pde,Y_test_bugs_pde = MLSE.classification_binary("differentSoftware/pde/pde_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_pde, y_resampled_pde = ros.fit_resample(X_train_pde, Y_train_bugs_pde)

X_train_lucene,Y_train_bugs_lucene,X_test_lucene,Y_test_bugs_lucene = MLSE.classification_binary("differentSoftware/lucene/lucene_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_lucene, y_resampled_lucene = ros.fit_resample(X_train_lucene, Y_train_bugs_lucene)

X_train_mylyn,Y_train_bugs_mylyn,X_test_mylyn,Y_test_bugs_mylyn = MLSE.classification_binary("differentSoftware/mylyn/mylyn_all_data.csv",
                                                                     'numberOfBugsFoundUntil',"wmc",0,
                                                                       "bugs")
X_resampled_mylyn, y_resampled_mylyn = ros.fit_resample(X_train_lucene, Y_train_bugs_lucene)


AlltheMatrix/differentSoftware/eclipse/eclipse_all_data.csv
lens: 50
start:2,end:43
(997,)
the data shape is (997, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[26 1 1 ... 0 3 263]
 [11 4 1 ... 3 3 62]
 [15 3 3 ... 2 7 46]
 ...
 [1 0 0 ... 4 8 23]
 [7 0 0 ... 0 5 48]
 [3 0 0 ... 1 8 26]] (698,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/equinox/equinox_all_data.csv
lens: 50
start:2,end:43
(324,)
the data shape is (324, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[1 0 0 ... 0 0 0]
 [1 0 0 ... 1 7 12]
 [1 0 0 ... 0 1 1]
 ...
 [4 0 0 ... 0 5 33]
 [1 0 0 ... 0 1 1]
 [3 1 0 ... 0 1 15]] (227,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/differentSoftware/pde/pde_all_data.csv
lens: 50
start:2,end:43
(1497,)
the data shape is (1497, 40)
<class 'numpy.ndarray'>
@@@@@@@@@@@@@@@@@@@@@@@@@@
[[0 0 0 ... 0 2 15]
 [3 0 0 ... 0 5 24]
 [0 0 0 ... 0 1 8]
 ...
 [5 0 0 ... 0 6 117]
 [1 0 0 ... 0 10 52]
 [3 0 0 ... 0 7 30]] (1048,)
@@@@@@@@@@@@@@@@@@@@@@@@@@
AlltheMatrix/

In [ ]:
??MLSE

In [ ]:
list11 = [X_resampled_eclipse, X_resampled_pde,X_resampled_equinox,X_resampled_lucene,X_resampled_mylyn]
list22 = [y_resampled_eclipse,y_resampled_pde,y_resampled_equinox,y_resampled_lucene,y_resampled_mylyn]
list33 = [X_test_eclipse, X_test_pde,X_test_equinox,X_test_lucene,X_test_mylyn]
list44 = [Y_test_bugs_eclipse,Y_test_bugs_pde,Y_test_bugs_equinox,Y_test_bugs_lucene,Y_test_bugs_mylyn]
list_name = ['X_train_eclipse', 'X_train_pde','X_train_equinox','X_train_lucene','X_train_mylyn']
import MLSE_Class as MLSE
for i in range(len(list11)):
    for j in range(len(list11)):
        print(list_name[i],list_name[j])
        result = MLSE.neuralNetworks(list11[i],list22[i],list33[j],list44[j])           
        print("·············~·······")

X_train_eclipse X_train_eclipse
The test accuracy score is 0.642809364548495
The test recall score is 0.6840579710144927
The test precision score is 0.3586016828809083
The test f1 score is 0.47018227512047417
·············~·······
X_train_eclipse X_train_pde
The test accuracy score is 0.6031180400890868
The test recall score is 0.7233333333333334
The test precision score is 0.2120281198224098
The test f1 score is 0.3276619192199281
·············~·······
X_train_eclipse X_train_equinox
The test accuracy score is 0.5402061855670104
The test recall score is 0.4727272727272728
The test precision score is 0.5066474615531219
The test f1 score is 0.4846884894307994
·············~·······
X_train_eclipse X_train_lucene
The test accuracy score is 0.633816425120773
The test recall score is 0.5700000000000001
The test precision score is 0.14564880987306617
The test f1 score is 0.2317596786998552
·············~·······
X_train_eclipse X_train_mylyn
The test accuracy score is 0.5413237924865832
The t

In [9]:
result

In [11]:
from imblearn.combine import SMOTEENN
smote_enn = SMOTEENN(random_state=0)
X_resampled_eclipse, y_resampled_eclipse = smote_enn.fit_resample(X_train_eclipse, Y_train_bugs_eclipse)
X_resampled_equinox, y_resampled_equinox = smote_enn.fit_resample(X_train_equinox, Y_train_bugs_equinox)
X_resampled_pde, y_resampled_pde = smote_enn.fit_resample(X_train_pde, Y_train_bugs_pde)
X_resampled_lucene, y_resampled_lucene = smote_enn.fit_resample(X_train_lucene, Y_train_bugs_lucene)
X_resampled_mylyn, y_resampled_mylyn = smote_enn.fit_resample(X_train_lucene, Y_train_bugs_lucene)

In [13]:
list11 = [X_resampled_eclipse, X_resampled_pde,X_resampled_equinox,X_resampled_lucene,X_resampled_mylyn]
list22 = [y_resampled_eclipse,y_resampled_pde,y_resampled_equinox,y_resampled_lucene,y_resampled_mylyn]
list33 = [X_test_eclipse, X_test_pde,X_test_equinox,X_test_lucene,X_test_mylyn]
list44 = [Y_test_bugs_eclipse,Y_test_bugs_pde,Y_test_bugs_equinox,Y_test_bugs_lucene,Y_test_bugs_mylyn]
list_name = ['X_train_eclipse', 'X_train_pde','X_train_equinox','X_train_lucene','X_train_mylyn']
for i in range(len(list11)):
    for j in range(len(list11)):
        print(list_name[i],list_name[j])
        if (i!=j):
            MLSE.RandomForest(list11[i],list22[i],list33[j],list44[j])
        elif (i==j):
            MLSE.RandomForest(list11[i],list22[i],list33[j],list44[j])           
        print("·············~·······")

X_train_eclipse X_train_eclipse
The test accuracy score is 0.8321608040201005
The test recall score is 0.8514285714285714
The test precision score is 0.5141026087819436
The test f1 score is 0.6409229970921655
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_pde
The test accuracy score is 0.737123745819398
The test recall score is 0.574468085106383
The test precision score is 0.3156302038472581
The test f1 score is 0.4072066571538334
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_equinox
The test accuracy score is 0.7569230769230769
The test recall score is 0.45714285714285713
The test precision score is 0.6864468864468863
The test f1 score is 0.5482726423902895
~~~~~~~~~~~~~~~~~~~~~~~~~~~
·············~·······
X_train_eclipse X_train_lucene
The test accuracy score is 0.8579710144927537
The test recall score is 0.411764705882353
The test precision score is 0.4218954248366013
The test f1 score is 0.4165418894830659
~~~~~~~~~~~~~~~~~~~~~

$g(z) = \frac{1}{1 + exp(-z)}$

$(\beta ) = \frac{1}{m} \sum_{i=1}^m[-y_i log(h_\beta (x_i) – (1 – y_i) log(1-h_\beta (x_i))$